### ISSUE TITLE
rust beta fails when reading dependencies

### ISSUE THREAD

**Issue by epage** [budziq/rust-skeptic#65] opened 2017-10-17 01:19 UTC
- Reproduces with Beta only.  Stable and Nightly are fine.
- Seen on all new PRs for both liquid-rust and assert_cli
- Example PR: https://github.com/killercup/assert_cli/pull/50

```
---- readme_sect_example_line_30 stdout ----
        thread 'readme_sect_example_line_30' panicked at 'failed to read dependencies: Error(Toml(Error { inner: ErrorInner { kind: Custom, line: None, col: 0, message: "missing field `root`", key: [] } }), State { next_error: None, backtrace: Some(stack backtrace:
   0:     0x7f2fab8fb275 - backtrace::backtrace::libunwind::trace
                        at /home/epage/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.3/src/backtrace/libunwind.rs:53
   1:     0x7f2fab8f065b - backtrace::backtrace::trace<closure>
                        at /home/epage/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.3/src/backtrace/mod.rs:42
   2:     0x7f2fab8ee43f - backtrace::capture::{{impl}}::new_unresolved
                        at /home/epage/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.3/src/capture.rs:88
   3:     0x7f2fab8ee39e - backtrace::capture::{{impl}}::new
                        at /home/epage/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.3/src/capture.rs:63
   4:     0x7f2fab8eb664 - error_chain::make_backtrace
                        at /home/epage/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.11.0/src/lib.rs:616
   5:     0x7f2fab8eb6df - error_chain::{{impl}}::default
                        at /home/epage/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.11.0/src/lib.rs:710
   6:     0x7f2fab8210dc - skeptic::rt::{{impl}}::from_kind
                        at /home/epage/git/assert_cli/<impl_error_chain_processed macros>:53
   7:     0x7f2fab821216 - skeptic::rt::{{impl}}::from
                        at /home/epage/.cargo/registry/src/github.com-1ecc6299db9ec823/skeptic-0.13.0/lib.rs:526
   8:     0x7f2fab81d32c - skeptic::rt::{{impl}}::from_path<std::path::PathBuf>
                        at /home/epage/.cargo/registry/src/github.com-1ecc6299db9ec823/skeptic-0.13.0/lib.rs:574
   9:     0x7f2fab81f5c4 - skeptic::rt::get_rlib_dependencies::{{closure}}<std::path::PathBuf>
                        at /home/epage/.cargo/registry/src/github.com-1ecc6299db9ec823/skeptic-0.13.0/lib.rs:649
  10:     0x7f2fab81a80e - core::result::{{impl}}::or_else<skeptic::rt::CargoLock,skeptic::rt::Error,skeptic::rt::Error,closure>
                        at /checkout/src/libcore/result.rs:686
  11:     0x7f2fab81e5fa - skeptic::rt::get_rlib_dependencies<std::path::PathBuf>
                        at /home/epage/.cargo/registry/src/github.com-1ecc6299db9ec823/skeptic-0.13.0/lib.rs:642
  12:     0x7f2fab8203ad - skeptic::rt::compile_test_case
                        at /home/epage/.cargo/registry/src/github.com-1ecc6299db9ec823/skeptic-0.13.0/lib.rs:770
  13:     0x7f2fab81fd85 - skeptic::rt::run_test
                        at /home/epage/.cargo/registry/src/github.com-1ecc6299db9ec823/skeptic-0.13.0/lib.rs:716
  14:     0x7f2fab81656a - skeptic::readme_sect_example_line_30
                        at /home/epage/git/assert_cli/target/debug/build/assert_cli-bf15821e1bb9616a/out/skeptic-tests.rs:21
  15:     0x7f2fab8ca871 - test::run_test::{{closure}}
                        at /checkout/src/libtest/lib.rs:1480
                         - core::ops::function::FnOnce::call_once<closure,(())>
                        at /checkout/src/libcore/ops/function.rs:223
                         - test::{{impl}}::call_box<(),closure>
                        at /checkout/src/libtest/lib.rs:141
  16:     0x7f2fab95cf2c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  17:     0x7f2fab8bbd9a - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /checkout/src/libstd/panicking.rs:459
                         - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panic.rs:361
                         - test::run_test::run_test_inner::{{closure}}
                        at /checkout/src/libtest/lib.rs:1419
                         - std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>
                        at /checkout/src/libstd/sys_common/backtrace.rs:134
  18:     0x7f2fab8bcb82 - std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:400
                         - std::panic::{{impl}}::call_once<(),closure>
                        at /checkout/src/libstd/panic.rs:296
                         - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panicking.rs:480
  19:     0x7f2fab95cf2c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  20:     0x7f2fab8c4642 - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /checkout/src/libstd/panicking.rs:459
                         - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panic.rs:361
                         - std::thread::{{impl}}::spawn::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:399
                         - alloc::boxed::{{impl}}::call_box<(),closure>
                        at /checkout/src/liballoc/boxed.rs:726
  21:     0x7f2fab954ffb - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:736
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:24
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:90
  22:     0x7f2faadc76b9 - start_thread
  23:     0x7f2faa8d73dc - clone
  24:                0x0 - <unknown>) })', /checkout/src/libcore/result.rs:906:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::expect
             at /checkout/src/libcore/result.rs:799
  11: skeptic::rt::compile_test_case
             at /home/epage/.cargo/registry/src/github.com-1ecc6299db9ec823/skeptic-0.13.0/lib.rs:770
  12: skeptic::rt::run_test
             at /home/epage/.cargo/registry/src/github.com-1ecc6299db9ec823/skeptic-0.13.0/lib.rs:716
  13: skeptic::readme_sect_example_line_30
             at ./target/debug/build/assert_cli-bf15821e1bb9616a/out/skeptic-tests.rs:21
  14: <F as test::FnBox<T>>::call_box
             at /checkout/src/libtest/lib.rs:1480
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/libtest/lib.rs:141
  15: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
```

**Comment by epage** [comment] 2017-10-17 02:59
Oddly enough, its only our Linux builds that are failing and not Windows.  Caching is currently disabled in the Windows CI.

**Comment by budziq** [comment] 2017-10-17 05:43
Thanks! It looks like it is caused by https://github.com/rust-lang/cargo/pull/4571.
No idea yet why it still works on nightly.

**Comment by budziq** [comment] 2017-10-17 09:00
Note to self.
Fill need to stop parsing Cargo.lock and start parsing `cargo metadata --format-version 1` (we will be able to drop Toml dependency)
or better yet [cargo_metadata](https://crates.io/crates/cargo_metadata) crate

**Comment by epage** [comment] 2017-10-17 14:01
Odd things
- Only on beta
- Only on Linux
- Some of the skeptic tests pass

**Comment by budziq** [comment] 2017-10-18 16:35
tested #66 against assert_cli and liquid and it fixes the problem. Will still need to check the gnu windows CI fails and push new version to crates.io later this week.

**Comment by budziq** [comment] 2017-10-19 13:53
@epage [0.13.2](https://crates.io/crates/skeptic/0.13.2) was published to crates.io. This should fix this problem in liquid and assert_cli. Please check if it's ok now.

**Comment by epage** [comment] 2017-10-19 15:06
Looks good to me!

**Comment by budziq** [comment] 2017-10-19 15:07
cool! closing

**Closed as completed by budziq** 2017-10-19 15:07 UTC
